# Generated by Django 5.2.16 on 2026-07-28 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('direction', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('normalized_plate', models.CharField(max_length=32, unique=True)),
                ('display_plate', models.CharField(max_length=32)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('manual_review', 'Manual review')], max_length=16)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('access_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='domain.accesslist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_rules', to='domain.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AccessDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('manual_review', 'Manual review')], max_length=16)),
                ('reason', models.CharField(max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='domain.accessrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='domain.gate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarrierCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barrier_commands', to='domain.accessdecision')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barrier_commands', to='domain.gate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=120)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gate',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gates', to='domain.parkingsite'),
        ),
        migrations.AddField(
            model_name='accesslist',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_lists', to='domain.parkingsite'),
        ),
        migrations.CreateModel(
            name='RecognitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('normalized_plate', models.CharField(max_length=32)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('captured_at', models.DateTimeField()),
                ('retention_expires_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_events', to='domain.camera')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accessdecision',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='domain.recognitionevent'),
        ),
        migrations.AddConstraint(
            model_name='gate',
            constraint=models.UniqueConstraint(fields=('site', 'external_id'), name='unique_gate_external_id'),
        ),
        migrations.AddConstraint(
            model_name='accesslist',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_access_list_name'),
        ),
        migrations.AddIndex(
            model_name='recognitionevent',
            index=models.Index(fields=['camera', 'captured_at'], name='domain_reco_camera__6fe5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionevent',
            index=models.Index(fields=['normalized_plate', 'captured_at'], name='domain_reco_normali_390472_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrule',
            index=models.Index(fields=['vehicle', 'is_active', 'priority'], name='domain_acce_vehicle_527fda_idx'),
        ),
    ]
