# Generated by Django 5.2.16 on 2026-07-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslist',
            name='kind',
            field=models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], default='whitelist', max_length=16),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='allowed_from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='allowed_until_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='allowed_weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_rules', to='domain.gate'),
        ),
    ]
