# Generated by Django 5.2 on 2026-07-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("domain", "0002_accesslist_kind_accessrule_allowed_from_time_and_more")]

    operations = [
        migrations.RenameField(
            model_name="recognitionevent",
            old_name="request_id",
            new_name="recognition_request_id",
        ),
    ]
