# Generated by Django 6.0.7 on 2026-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0003_rename_request_id_recognition_request_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="recognitionevent",
            name="image_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
